lane :test do
  dependency_check_ios_analyzer(
    project_name: 'SampleProject',
    project_path: 'sample-project',
    output_types: 'all',
    keep_binary_on_exit: false,
    fail_on_cvss: 7
  )
end

lane :test_on_fail do
  begin
    dependency_check_ios_analyzer(
      project_name: 'SampleProject',
      project_path: 'sample-project',
      skip_spm_analysis: true,
      output_types: 'html, junit',
      fail_on_cvss: 3
    )
  rescue
    UI.important("It's all good!")
    next
  end

  UI.user_error!("Analyzer missed the vulnerability!")
end
